set lower and upper limit for partitions
dfds/capability-service pull request #73
Opened 2020-01-22 14:39 UTC by kim-lindhard-dfds

2020-01-27 11:26 UTC, wcarlsen commented on src/CapabilityService.WebApi/Infrastructure/Api/ExceptionToStatusCode.cs
>  					return null;
null result isn't sufficient

2020-01-27 11:26 UTC, wcarlsen requested changes
Again with the case switches man ;-)

2020-01-28 11:41 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |5|
| **Quality Gates** |Fail|
| **Description** |The change is medium risk, adds 150 lines, deletes 66 lines of code in 6 files, which is more than your typical change set. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul><br/>Degrades in Code Health<br/><ul><li>CapabilityController.cs degrades from a Code Health of 9 -> 8.67</li></ul>|
| **Code Health Delta Descriptions:** |CapabilityController.cs<br/><ul><li> **Degradations:** <ul><li>Code Duplication - getting worse</li></ul></li></ul>|

2020-01-28 13:39 UTC, wcarlsen approved these changes
Great man. Good work

2020-02-13 05:32 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |5|
| **Quality Gates** |Fail|
| **Description** |The change is medium risk, adds 150 lines, deletes 66 lines of code in 6 files, which is more than your typical change set. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul><br/>Degrades in Code Health<br/><ul><li>CapabilityController.cs degrades from a Code Health of 9 -> 8.67</li></ul>|
| **Code Health Delta Descriptions:** |CapabilityController.cs<br/><ul><li> **Degradations:** <ul><li>Code Duplication - getting worse</li></ul></li></ul>|

2020-02-13 13:22 UTC, merged