Ch1148/capsvc call kafka janitor s api for topic
dfds/capability-service pull request #88
Opened 2020-02-17 09:10 UTC by SEQUOIIA

2020-02-17 09:10 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |7|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 126 lines, deletes 24 lines of code in 9 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 04:47 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 219 lines, deletes 55 lines of code in 14 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>5 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 04:56 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 219 lines, deletes 96 lines of code in 14 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>5 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 05:05 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 263 lines, deletes 114 lines of code in 15 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 05:07 UTC, kim-lindhard-dfds requested changes

2020-02-20 05:07 UTC, kim-lindhard-dfds commented on src/CapabilityService.WebApi/Features/Kafka/Domain/Events/TopicCreated.cs
> +		[JsonConverter(typeof(TopicNameConverter))]
Our domain should never concern itself with transport, what is the issue we are solving with the converter?

2020-02-20 05:07 UTC, kim-lindhard-dfds commented on src/CapabilityService.WebApi/Infrastructure/Persistence/CapabilityServiceDbContext.cs
> +﻿using DFDS.CapabilityService.WebApi.Domain.Models;
Seems like line endlings

2020-02-20 06:38 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 263 lines, deletes 114 lines of code in 15 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 06:42 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 269 lines, deletes 134 lines of code in 16 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 08:47 UTC, SEQUOIIA commented on src/CapabilityService.WebApi/Features/Kafka/Domain/Events/TopicCreated.cs
> +		[JsonConverter(typeof(TopicNameConverter))]
It solves the issue of 

{
  "Name": {
      "name": "here"
    },
    "Description": "This is a thing",
    ....
}

2020-02-20 08:48 UTC, SEQUOIIA commented on src/CapabilityService.WebApi/Infrastructure/Persistence/CapabilityServiceDbContext.cs
> +﻿using DFDS.CapabilityService.WebApi.Domain.Models;
Yes.

2020-02-20 10:00 UTC, kim-lindhard-dfds commented
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |The change is high risk and adds 271 lines, deletes 158 lines of code in 16 files. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>6 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamemd. Skipping code health checks for those files.</li></ul>|

2020-02-20 10:02 UTC, kim-lindhard-dfds approved these changes

2020-02-20 10:02 UTC, merged